name: Question
description: Ask a question about usage, behavior, or setup
title: "[QUESTION] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you need help with?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Any relevant details, links, or setup information

  - type: textarea
    id: tried
    attributes:
      label: What have you tried?
      description: Describe what you’ve already attempted (if applicable)
