name: Idea
description: Share an idea or general suggestion
title: "[IDEA] "
labels: ["idea"]
body:
  - type: textarea
    id: idea
    attributes:
      label: Your Idea
      description: Describe your idea or suggestion
      placeholder: It would be nice if...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Optional background, examples, or links
